[tool.poetry]
name = "fedora"
version = "0.1.0"
description = ""
authors = ["Asim Ukaye <asim.ukaye@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
flwr = "^1.11.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
