%YAML 1.2
---
# mode: fedavg
# mode: centralized
mode: debug
desc: "FedAvg run with fednet model and cifar10 dataset, iid, 500 rounds, 1 epoch, no resize"
# desc: "Centralized training w epochs and rounds interchanged. sanity check"


defaults:
  - base_config
  - hydra: custom
  - server: baseflower
  - strategy: base
  # - strategy: fedavgmanual
  # - strategy: fedstdev
  # - strategy: fedgradstd
  # - strategy: fedopt
  # - strategy: cgsv
  # - client: fedstdev
  # - client: fedgradstd
  - client: baseflower
  - dataset: cifar10
  - split: iid

  # - dataset: bloodmnist
  # - dataset: fedisic
  # - model: resnet18gn
  # - model: resnet18
  # - model: twocnn
  - model: fednet
  - _self_

simulator:
  # Simulator Mode: Takes arguments 'federated', 'standalone' or 'centralized', 'flower'
  # mode: standalone
  # mode: centralized
  device: auto
  mode: federated
  # mode: flower 
  seed: 42
  # use_tensorboard: false
  # use_wandb: true
  # save_csv: true
  # out_prefix: ''
  num_clients: 6
  num_rounds: 500
  checkpoint_every: 10
  # eval_type: both
  # eval_every: 1
  # flwr_resources:
  #   num_cpus: 2
  #   num_gpus: 0.5 #TODO: Couple this with device init

result:
  use_tensorboard: false
  use_wandb: true
  save_csv: true
  # out_prefix: ''


train_cfg:
  epochs: 1
  batch_size: 128
  eval_batch_size: 128
  optimizer:
    name: sgd
    lr: 0.01
  loss_name: crossentropy
  lr_scheduler:
    name: exponential
    gamma: 0.977 # lr_decay
  metric_cfg:
    eval_metrics: ['acc1']
    file_prefix: ''
    log_to_file: false

# CONFIG OVERRIDES

dataset:
  # subsample: false
  subsample_fraction: 1.0 # Fraction of the dataset to use. Only works when subsample is true

model_init:
  init_type: xavier
  init_gain: 1.0


# client:
#   cfg:
#     data_shuffle: True



# ########## OVERRIDES END HERE ##########
# Log Configuration: Additional configurations to be copied in the results summary section. Must be a valid configuration from the config tree.
# Experiment mode: Switch between debug and experiment methods
# mode: fedstdev_centralized
# mode: centralized
# mode: fedavg_patho
# mode: fedavg_dirichlet
# mode: fedavgmanual
# mode: standalone
# mode: fedstdev
# mode: fedgradstd
# mode: fedgradstd_patho
# mode: fedgradstd_dirichlet
# mode: fedopt_patho
# mode: fedopt
# mode: debug
# mode: cgsv
# desc: 'Centralized run with three label flipped client'
# desc: 'Centralized run with three noisy client'
# desc: 'Fedgradstd client dirichlet split with equal weighting strategy'
# desc: 'Fedgradstd client with equal weighting strategy'
# desc: 'Fedgradstd dry runs for analyzing different metrics with three label flipped clients and 25 % data'
# desc: 'Fedgradstd run with dirichlet split,5 shuffles only'
# desc: 'Fedavg run with bloodmnist iid'
# desc: 'Centralized run with bloodmnist iid'

# desc: Fedopt with patho split
# desc: CGSV run with three label fliped clients
# desc: 'Fedavg run with dirichlet split, alpha 10000, checking dirichlet correctness'
# desc: 'Fedavg manual run with three noisy clients'

# desc: 'Fedavg manual run with three label flipped client'


log_cfg: []

...