%YAML 1.2
---
# mode: rffl
# mode: centralized
mode: debug
desc: "RFFL run with iid cidar 10 dataset, fednet model, and baseflower client, 500 rounds 1 epoch "
# desc: "Centralized training w epochs and rounds interchanged. sanity check"

defaults:
  - base_config
  - hydra: custom
  - server: baseflower
  # - strategy: base
  # - strategy: fedavgmanual
  # - strategy: fedstdev
  # - strategy: fedgradstd
  # - strategy: fedopt
  - strategy: rffl
  # - client: fedstdev
  # - client: fedgradstd
  - client: baseflower
  - dataset: cifar10
  - split: iid

  # - dataset: bloodmnist
  # - dataset: fedisic
  # - model: resnet18gn
  # - model: resnet18
  # - model: twocnn
  - model: fednet
  - _self_

simulator:
  # Simulator Mode: Takes arguments 'federated', 'standalone' or 'centralized', 'flower'
  # mode: standalone
  # mode: centralized
  mode: federated
  # mode: flower
  device: auto
  seed: 42
  num_clients: 6
  num_rounds: 500
  checkpoint_every: 20

result:
  use_tensorboard: false
  use_wandb: true
  save_csv: true
  # out_prefix: ''


train_cfg:
  epochs: 1
  batch_size: 128
  eval_batch_size: 128
  optimizer:
    name: sgd
    lr: 0.01
  loss_name: crossentropy
  lr_scheduler:
    name: exponential
    gamma: 0.977 # lr_decay
  metric_cfg:
    eval_metrics: ['acc1']
    file_prefix: ''
    log_to_file: false

# CONFIG OVERRIDES

dataset:
  subsample_fraction: 1.0 # Fraction of the dataset to use. Only works when subsample is true

model_init:
  init_type: xavier
  init_gain: 1.0


# client:
#   cfg:
#     data_shuffle: True



# ########## OVERRIDES END HERE ##########
# Log Configuration: Additional configurations to be copied in the results summary section. Must be a valid configuration from the config tree.
log_cfg: []


...