%YAML 1.2
---
mode: ties
# mode: debug
desc: "Ties with twocnn model and cifar10 dataset, patho 3 cls/client, K = 0.2, lamba = 1.0, 200 rounds, 1 epochs"

defaults:
  - base_config
  - hydra: custom
  - server: baseflower
  - strategy: ties
  - client: baseflower
  - dataset: cifar10
  - split: iid
  # - dataset: bloodmnist
  # - dataset: fedisic
  # - model: resnet18gn
  # - model: resnet18
  - model: twocnn
  - _self_

simulator:
  # Simulator Mode: Takes arguments 'federated', 'standalone' or 'centralized', 'flower'
  mode: federated
  # mode: flower 
  seed: 42
  use_tensorboard: false
  use_wandb: true
  save_csv: true
  out_prefix: ''
  num_clients: 6
  num_rounds: 200
  checkpoint_every: 10
  eval_type: both
  eval_every: 1
  flwr_resources:
    num_cpus: 2
    num_gpus: 0.5 #TODO: Couple this with device init

train_cfg:
  epochs: 1
  device: auto
  batch_size: 128
  eval_batch_size: 128
  optimizer:
    name: sgd
    lr: 0.01
  loss_name: crossentropy
  lr_scheduler:
    name: exponential
    gamma: 0.977 # lr_decay
  metric_cfg:
    eval_metrics: ['acc1']
    file_prefix: ''
    log_to_file: false

# CONFIG OVERRIDES

dataset:
  subsample: false
  subsample_fraction: 1.0 # Fraction of the dataset to use. Only works when subsample is true

model_init:
  init_type: xavier
  init_gain: 1.0

strategy:
  cfg:
    K: 0.2
    lamda: 1.0

# client:
#   cfg:
#     data_shuffle: True

log_cfg: []

...